# 머씬러닝 완벽가이드

## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

In [5]:
import numpy as np

### 단일값 추출

In [9]:
# 1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:', array1)

value=array1[2] # array1의 인덱스 2번값
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [10]:
# ndarray 내의 데이터값 간단히 수정
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [11]:
# 다차원 ndarrary에서 단일값 추출.
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=1, col=1) index 가리키는 값:', array2d[1,1])

(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=1, col=1) index 가리키는 값: 5


### 슬라이싱

In [13]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3] # 인덱스 0이상 3 미만까지 잘라서 array3에 저장
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [14]:
# 첫 인덱스부터 3번째 인덱스 미만까지
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

[1 2 3]


In [15]:
# 3부터 마지막 인덱스까지
array5=array1[3:]
print(array5)

[4 5 6 7 8 9]


In [16]:
# ':' 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/ 맨 마지막 인덱스로 간주함.
array6=array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [17]:
# 2차원 ndarray 글라이싱
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [18]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

#### 리스트나 ndarray로 인덱ㅅ, 집합을 지정하면 해당 위치의 인덱싱에 해당하는 ndarray를 반환하는 인덱싱 방식

In [19]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

In [20]:
array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array2d[[0,1],2] => [3, 6]


In [21]:
array4=array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2]=>', array4.tolist())

array2d[[0,1], 0:2]=> [[1, 2], [4, 5]]


In [22]:
array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

##### 조건 필터링과 검색을 동시에 할 수 있는 인덱싱 방법.

In [23]:
array1d=np.arange(start=1, stop=10)
# [] 안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d > 5] # 데이터값이 5보다 큰 데이터만 추출. for loop, if 문보다 훨씬 간단함.
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [24]:
# 그냥 조건식만 쓰면,
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

## 행렬의 정렬 - sort()와 argsort()

### 행렬 정렬

##### np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
##### ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None.

In [27]:
org_array=np.array([3,1,9,5])
print('원본행렬', org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2=org_array.sort() # 배열이름.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

원본행렬 [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [28]:
sort_array1_desc=np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [29]:
# 행렬이 2차원인 경우
array2d=np.array([[8, 12],
                 [7,1]])

sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

In [31]:
# np.argsort(): 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때.
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [35]:
sort_indices_desc=np.argsort(org_array)[::-1]
print('내림차순으로 정렬:', sort_indices_desc)

내림차순으로 정렬: [2 3 0 1]


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

In [37]:
# np.dot(): 행렬 내적, 행렬 곱. 왼쪽 행렬의 행과 오른쪽 행렬의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬

In [38]:
# 전치행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
# transpose()
A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [42]:
B=np.array([[1,2],
          [3,4],
          [5,6]])
transpose_matB=np.transpose(B)
print(B)
print(transpose_matB)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
